### ISSUE TITLE
Error starting the bridge

### ISSUE THREAD

**Issue by T0MuX** [ace13/matrix-puppet-steam#3]
I'm facing an issue starting the bridge. I followed instructions, but I get this error : 
```
$ node index.js -c config.json
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Got push rules
synced
TypeError: expecting an array or an iterable object but got [object Null]
    at apiRejection (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/promise.js:10:27)
    at ReductionPromiseArray.init (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/promise_array.js:63:19)
    at new ReductionPromiseArray (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/reduce.js:30:10)
    at reduce (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/reduce.js:132:17)
    at Promise.reduce (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/reduce.js:117:12)
    at Function.PromiseMapSeries [as mapSeries] (/opt/matrix-puppet-steam/node_modules/bluebird/js/release/each.js:11:12)
    at bridge.run.then.then (/opt/matrix-puppet-steam/index.js:93:22)
    at tryCatcher (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/matrix-puppet-steam/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by ananace** [comment]
The bridge is not really in a usable state at the moment, the master branch never got to a working state as I started redoing it on the matrix-puppet-server design rather early on in the develop branch.  
That branch is functional to the point where it implements all the communication logic, it just won't sync any users or rooms for you, so you need to manually map the MXIDs to the right SteamID to be able to use it. (The MXID mapping is done with 64-bit SteamIDs, written in base 36)

I've been planning on picking this up again, but so many things have been in the way that I haven't had the time as of yet to restart work on it.

But hey, with the new Steam chat UI I won't have to worry about trying to figure out group chats, as they don't have a stable API that I can use to access them any more, so this bridge can only really be used for 1:1 chats.

**Comment by T0MuX** [comment]
Hi, thank you for answering :) 

Sorry I don't understand everything in what you said, I don't know how to to do what you say (mapping MXID to SteamID). I have low level in this kind of stuff ^^
I fired up my own matrix homeserver (with somes others services, hosted on a VPS) and I use some bridges/puppets for my personnal use. It's really useful ! So I want to setup the steam bridge/puppet, just to add another network to my network family lol.

Can you, if you have time, help me to do what you said ? Or maybe you will write a little howto in the readme ?

**Comment by ananace** [comment]
A little how-to at this point would probably just be a sentence to the tune of;  
"Wait until the bridge is in a more functional state"

At the moment, the only thing that's bridged is message transfers themselves, and nothing more than that. So in order to use the bridge at its current state you'd need to be able to do the user mapping and room setup yourself, which is not really something that can be described by a how-to as it's quite technical and depends on understanding how the code converts between Steam and Matrix IDs and types.

**Comment by T0MuX** [comment]
Okay thank you for your explanation.
